=== irivengroup/WorldCountriesDatas/src/data/schema/country.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "CountryInfo",
  "type": "object",
  "required": [
    "alpha2",
    "alpha3",
    "numeric_code",
    "country_name"
  ],
  "properties": {
    "alpha2": {
      "type": "string"
    },
    "alpha3": {
      "type": "string"
    },
    "numeric_code": {
      "type": "string"
    },
    "country_name": {
      "type": "string"
    },
    "capital": {
      "type": "string"
    },
    "tld": {
      "type": "string"
    },
    "region_alpha_code": {
      "type": "string"
    },
    "region_num_code": {
      "type": "string"
    },
    "region_name": {
      "type": "string"
    },
    "sub_region_code": {
      "type": "string"
    },
    "sub_region_name": {
      "type": "string"
    },
    "language": {
      "type": "string"
    },
    "currency_code": {
      "type": "string"
    },
    "currency_name": {
      "type": "string"
    },
    "postal_code_pattern": {
      "type": "string"
    },
    "phone_code": {
      "type": "string"
    },
    "intl_dialing_prefix": {
      "type": "string"
    },
    "natl_dialing_prefix": {
      "type": "string"
    },
    "subscriber_phone_pattern": {
      "type": "string"
    }
  }
}

=== irivengroup/WorldCountriesDatas/src/data/.countriesRepository.json
[
  {
    "alpha2": "AD",
    "alpha3": "AND",
    "numeric_code": "020",
    "country_name": "Andorra",
    "capital": "Andorra la Vella",
    "tld": ".ad",
    "region_alpha_code": "EU",
    "region_num_code": "150",
    "region_name": "Europe",
    "sub_region_code": "039",
    "sub_region_name": "Southern Europe",
    "language": "ca",
    "currency_code": "EUR",
    "currency_name": "Euro",
    "postal_code_pattern": "^(?:AD)*(\\d{3})$",
    "phone_code": "376",
    "intl_dialing_prefix": "00",
    "natl_dialing_prefix": "",
    "subscriber_phone_pattern": "[78]\\d{5}|(?:3\\d|6(?:[0-8]|90\\d{2}))\\d{4}|180[02]\\d{4}|[19]\\d{5}"
  },
  {
    "alpha2": "AE",
    "alpha3": "ARE",
    "numeric_code": "784",
    "country_name": "United Arab Emirates",
    "capital": "Abu Dhabi",
    "tld": ".ae",
    "region_alpha_code": "AS",
    "region_num_code": "142",
    "region_name": "Asia",
    "sub_region_code": "145",
    "sub_region_name": "Western Asia",
    "language": "ar-AE,fa,en,hi,ur",
    "currency_code": "AED",
    "currency_name": "UAE Dirham",
    "postal_code_pattern": "",
    "phone_code": "971",
    "intl_dialing_prefix": "00",
    "natl_dialing_prefix": "0",
    "subscriber_phone_pattern": "[2-4679][2-8]\\d{6}|5[024-68]\\d{7}|400\\d{6}|800\\d{2,9}|900[02]\\d{5}|700[05]\\d{5}|600[25]\\d{5}"
  },
  {
    "alpha2": "AF",
    "alpha3": "AFG",
    "numeric_code": "004",
    "country_name": "Afghanistan",
    "capital": "Kabul",
    "tld": ".af",
    "region_alpha_code": "AS",
    "region_num_code": "142",
    "region_name": "Asia",
    "sub_region_code": "034",
    "sub_region_name": "Southern Asia",
    "language": "fa-AF,ps,uz-AF,tk",
    "currency_code": "AFN",
    "currency_name": "Afghani",
    "postal_code_pattern": "",
    "phone_code": "93",
    "intl_dialing_prefix": "00",
    "natl_dialing_prefix": "0",
    "subscriber_phone_pattern": "(?:[25][0-8]|[34][0-4]|6[0-5])[2-9]\\d{6}|7(?:[014-9]\\d|2[89]|30)\\d{6}"
  },
  {
    "alpha2": "AG",
    "alpha3": "ATG",
    "numeric_code": "028",
    "country_name": "Antigua and Barbuda",
    "capital": "St. John's",
    "tld": ".ag",
    "region_alpha_code": "AM",
    "region_num_code": "019",
    "region_name": "Americas",
    "sub_region_code": "029",
    "sub_region_name": "Caribbean",
    "language": "en-AG",
    "currency_code": "XCD",
    "currency_name": "East Caribbean Dollar",
    "postal_code_pattern": "",
    "phone_code": "1",
    "intl_dialing_prefix": "011",
    "natl_dialing_prefix": "1",
    "subscriber_phone_pattern": "268(?:4(?:6[0-38]|84)|56[0-2])\\d{4}|268(?:464|7(?:2\\d|3[246]|64|7[0-689]|8[02-68]))\\d{4}|8(?:00|33|44|55|66|77|88)[2-9]\\d{6}|900[2-9]\\d{6}|5(?:00|22|33|44|66|77|88)[2-9]\\d{6}|26848[01]\\d{4}|26840[69]\\d{4}"
  },
  {
    "alpha2": "AI",
    "alpha3": "AIA",
    "numeric_code": "660",
    "country_name": "Anguilla",
    "capital": "The Valley",
    "tld": ".ai",
    "region_alpha_code": "AM",
    "region_num_code": "019",
    "region_name": "Americas",
    "sub_region_code": "029",
    "sub_region_name": "Caribbean",
    "language": "en-AI",
    "currency_code": "XCD",
    "currency_name": "East Caribbean Dollar",
    "postal_code_pattern": "",
    "phone_code": "1",
    "intl_dialing_prefix": "011",
    "natl_dialing_prefix": "1",
    "subscriber_phone_pattern": "2644(?:6[12]|9[78])\\d{4}|264(?:235|476|5(?:3[6-9]|8[1-4])|7(?:29|72))\\d{4}|8(?:00|33|44|55|66|77|88)[2-9]\\d{6}|900[2-9]\\d{6}|5(?:00|22|33|44|66|77|88)[2-9]\\d{6}"
  },
  {
    "alpha2": "AL",
    "alpha3": "ALB",
    "numeric_code": "008",
    "country_name": "Albania",
    "capital": "Tirana",
    "tld": ".al",
    "region_alpha_code": "EU",
    "region_num_code": "150",
    "region_name": "Europe",
    "sub_region_code": "039",
    "sub_region_name": "Southern Europe",
    "language": "sq,el",
    "currency_code": "ALL",
    "currency_name": "Lek",
    "postal_code_pattern": "",
    "phone_code": "355",
    "intl_dialing_prefix": "00",
    "natl_dialing_prefix": "0",
    "subscriber_phone_pattern": "(?:2(?:1(?:0[2-9]|[1-9]\\d)|[247]\\d{2}|[35][2-9]\\d|[68](?:0[2-9]|[1-9]\\d)|9(?:[089][2-9]|[1-7]\\d))|3(?:1(?:[04-9][2-9]|[1-3]\\d)|[2-6]\\d{2}|[79](?:[09][2-9]|[1-8]\\d)|8(?:0[2-9]|[1-9]\\d))|4\\d{3}|5(?:1(?:[05-9][2-9]|[1-4]\\d)|[2-578]\\d{2}|6(?:[06-9][2-9]|[1-5]\\d)|9(?:[089][2-9]|[1-7]\\d))|8(?:[19](?:[06-9][2-9]|[1-5]\\d)|[2-6]\\d{2}|[78](?:[089][2-9]|[1-7]\\d)))\\d{4}|6(?:[2-5][2-9]|[6-9]\\d)\\d{6}|800\\d{4}|900\\d{3}|808\\d{3}|700\\d{5}"
  },
  {
    "alpha2": "AM",
    "alpha3": "ARM",
    "numeric_code": "051",
    "country_name": "Armenia",
    "capital": "Yerevan",
    "tld": ".am",
    "region_alpha_code": "AS",
    "region_num_code": "142",
    "region_name": "Asia",
    "sub_region_code": "145",
    "sub_region_name": "Western Asia",
    "language": "hy",
    "currency_code": "AMD",
    "currency_name": "Armenian Dram",
    "postal_code_pattern": "^(\\d{6})$",
    "phone_code": "374",
    "intl_dialing_prefix": "00",
    "natl_dialing_prefix": "0",
    "subscriber_phone_pattern": "(?:1[0-2]\\d|2(?:2[2-46]|3[1-8]|4[2-69]|5[2-7]|6[1-9]|8[1-7])|3[12]2|47\\d)\\d{5}|(?:4[1349]|55|77|9[1-9])\\d{6}|800\\d{5}|90[016]\\d{5}|80[1-4]\\d{5}|60(?:2[078]|[3-7]\\d|8[0-5])\\d{4}"
  },
  {
    "alpha2": "AN",
    "alpha3": "ANT",
    "numeric_code": "530",
    "country_name": "Netherlands Antilles",
    "capital": "Willemstad",
    "tld": ".an",
    "region_alpha_code": "AM",
    "region_num_code": "019",
    "region_name": "Americas",
    "sub_region_code": "021",
    "sub_region_name": "Northern America",
    "language": "nl-AN,en,es",
    "currency_code": "ANG",
    "currency_name": "Netherlands Antillean Guilder",
    "postal_code_pattern": "",
    "phone_code": "599",
    "intl_dialing_prefix": "",
    "natl_dialing_prefix": "",
    "subscriber_phone_pattern": ""
  },
  {
    "alpha2": "AO",
    "alpha3": "AGO",
    "numeric_code": "024",
    "country_name": "Angola",
    "capital": "Luanda",
    "tld": ".ao",
    "region_alpha_code": "AF",
    "region_num_code": "002",
    "region_name": "Africa",
    "sub_region_code": "017",
    "sub_region_name": "Middle Africa",
    "language": "pt-AO",
    "currency_code": "AOA",
    "currency_name": "Kwanza",
    "postal_code_pattern": "",
    "phone_code": "244",
    "intl_dialing_prefix": "00",
    "natl_dialing_prefix": "",
    "subscriber_phone_pattern": "2\\d(?:[26-9]\\d|\\d[26-9])\\d{5}|9[1-49]\\d{7}"
  },
  {
    "alpha2": "AQ",
    "alpha3": "ATA",
    "numeric_code": "010",
    "country_name": "Antarctica",
    "capital": "",
    "tld": ".aq",
    "region_alpha_code": "AN",
    "region_num_code": "",
    "region_name": "",
    "sub_region_code": "",
    "sub_region_name": "",
    "language": "",
    "currency_code": "",
    "currency_name": "",
    "postal_code_pattern": "",
    "phone_code": "",
    "intl_dialing_prefix": "",
    "natl_dialing_prefix": "",
    "subscriber_phone_pattern": ""
  },
  {
    "alpha2": "AR",
    "alpha3": "ARG",
    "numeric_code": "032",
    "country_name": "Argentina",
    "capital": "Buenos Aires",
    "tld": ".ar",
    "region_alpha_code": "AM",
    "region_num_code": "019",
    "region_name": "Americas",
    "sub_region_code": "005",
    "sub_region_name": "South America",
    "language": "es-AR,en,it,de,fr,gn",
    "currency_code": "ARS",
    "currency_name": "Argentine Peso",
    "postal_code_pattern": "^[A-Z]?\\d{4}[A-Z]{0,3}$",
    "phone_code": "54",
    "intl_dialing_prefix": "00",
    "natl_dialing_prefix": "0",
    "subscriber_phone_pattern": "11\\d{8}|(?:2(?:2(?:[013]\\d|2[13-79]|4[1-6]|5[2457]|6[124-8]|7[1-4]|8[13-6]|9[1267])|3(?:1[467]|2[03-6]|3[13-8]|[49][2-6]|5[2-8]|[067]\\d)|4(?:7[3-8]|9\\d)|6(?:[01346]\\d|2[24-6]|5[15-8])|80\\d|9(?:[0124789]\\d|3[1-6]|5[234]|6[2-46]))|3(?:3(?:2[79]|6\\d|8[2578])|4(?:[78]\\d|0[0124-9]|[1-35]\\d|4[24-7]|6[02-9]|9[123678])|5(?:[138]\\d|2[1245]|4[1-9]|6[2-4]|7[1-6])|6[24]\\d|7(?:[0469]\\d|1[1568]|2[013-9]|3[145]|5[14-8]|7[2-57]|8[0-24-9])|8(?:[013578]\\d|2[15-7]|4[13-6]|6[1-357-9]|9[124]))|670\\d)\\d{6}|675\\d{7}|9(?:11[2-9]\\d{7}|(?:2(?:2[013]|3[067]|49|6[01346]|80|9[147-9])|3(?:36|4[12358]|5[138]|6[24]|7[069]|8[013578]))[2-9]\\d{6}|\\d{4}[2-9]\\d{5})|800\\d{7}|60[04579]\\d{7}|810\\d{7}"
  },
  {
    "alpha2": "AS",
    "alpha3": "ASM",
    "numeric_code": "016",
    "country_name": "American Samoa",
    "capital": "Pago Pago",
    "tld": ".as",
    "region_alpha_code": "OC",
    "region_num_code": "009",
    "region_name": "Oceania",
    "sub_region_code": "061",
    "sub_region_name": "Polynesia",
    "language": "en-AS,sm,to",
    "currency_code": "USD",
    "currency_name": "US Dollar",
    "postal_code_pattern": "",
    "phone_code": "1",
    "intl_dialing_prefix": "011",
    "natl_dialing_prefix": "1",
    "subscriber_phone_pattern": "6846(?:22|33|44|55|77|88|9[19])\\d{4}|684(?:2(?:5[2468]|72)|7(?:3[13]|70))\\d{4}|8(?:00|33|44|55|66|77|88)[2-9]\\d{6}|900[2-9]\\d{6}|5(?:00|22|33|44|66|77|88)[2-9]\\d{6}"
  },
  {
    "alpha2": "AT",
    "alpha3": "AUT",
    "numeric_code": "040",
    "country_name": "Austria",
    "capital": "Vienna",
    "tld": ".at",
    "region_alpha_code": "EU",
    "region_num_code": "150",
    "region_name": "Europe",
    "sub_region_code": "155",
    "sub_region_name": "Western Europe",
    "language": "de-AT,hr,hu,sl",
    "currency_code": "EUR",
    "currency_name": "Euro",
    "postal_code_pattern": "^(\\d{4})$",
    "phone_code": "43",
    "intl_dialing_prefix": "00",
    "natl_dialing_prefix": "0",
